language: node_js
node_js:
  - "0.10"
before_script:
- npm install grunt mocha jshint grunt-cli
- export HELLO=$HELLO
- echo $HELLO
- which grunt || echo "nope"
- which mocha || echo "nope"
- which jshint || echo "nope"
script:
- grunt jshint test
